# Solving Linear Systems

In [24]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

<h2>Linear Systems</h2>

<img src="linearmath4.png">

<h1>Gaussian elimination</h1>
The general procedure to solve a linear system of equation is called Gaussian elimination. The idea is to perform elementary row operations to reduce the system to its row echelon form and then solve.

<img src="linearmath5.png">

In [25]:
A = np.array([[1,1,2],[-1,3,1],[0,5,2]])
print(A)

[[ 1  1  2]
 [-1  3  1]
 [ 0  5  2]]


In [26]:
E1 = np.array([[1,0,3],[0,1,0],[0,0,1]])
print(E1)

[[1 0 3]
 [0 1 0]
 [0 0 1]]


In [27]:
E1 @ A

array([[ 1, 16,  8],
       [-1,  3,  1],
       [ 0,  5,  2]])

<img src="linearmath6.png">

In [28]:
E2 = np.array([[1,0,0],[0,-2,0],[0,0,1]])
print(E2)

[[ 1  0  0]
 [ 0 -2  0]
 [ 0  0  1]]


In [29]:
E2 @ A

array([[ 1,  1,  2],
       [ 2, -6, -2],
       [ 0,  5,  2]])

<img src="linearmath7.png">

In [30]:
E3 = np.array([[1,0,0],[0,0,1],[0,1,0]])
print(E3)

[[1 0 0]
 [0 0 1]
 [0 1 0]]


In [31]:
E3 @ A

array([[ 1,  1,  2],
       [ 0,  5,  2],
       [-1,  3,  1]])

<h3>Implementation</h3>
Let's write function to implement the elementary row operations. First of all, let's write a function called <b>add_rows</b> which takes input parameters <b><i>A, k, i</i></b> and <b><i>j</i></b> and returns the NumPy array resulting from adding <b><i>k</i></b> times row <b><i>j</i></b> to row <b><i>i</i></b> in the matrix <b><i>A</i></b>. If <b><i>i=j</i></b> , then let's say that the function scales row <b><i>i</i></b> by <b><i>k+1</i></b> since this would be the result of <b><i>k</i></b> times row <b><i>i</i></b> added to row <b><i>i</i></b>.

In [32]:
def add_row(A,k,i,j):
    "Add k times row j to row i in matrix A."
    n = A.shape[0]
    E = np.eye(n)
    if i == j:
        E[i,i] = k + 1
    else:
        E[i,j] = k
    return E @ A

Let's test our function:

In [33]:
M = np.array([[1,1],[3,2]])
print(M)

[[1 1]
 [3 2]]


In [34]:
add_row(M,2,0,1)

array([[7., 5.],
       [3., 2.]])

In [35]:
add_row(M,3,1,1)

array([[ 1.,  1.],
       [12.,  8.]])

Let's write a function called <b>scale_row</b> which takes 3 input parameters <b><i>A,k</i></b> and <b><i>i</i></b> and returns the matrix that results from <b><i>k</i></b> times row <b><i>i</i></b> in the matrix <b><i>A</i></b>.

In [36]:
def scale_row(A,k,i):
    "Multiply row i by k in matrix A."
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = k
    return E @ A

In [37]:
M = np.array([[3,1],[-2,7]])
print(M)

[[ 3  1]
 [-2  7]]


In [38]:
scale_row(M,3,1)

array([[ 3.,  1.],
       [-6., 21.]])

In [39]:
A = np.array([[1,1,1],[1,-1,0]])
print(A)

[[ 1  1  1]
 [ 1 -1  0]]


In [40]:
scale_row(A,5,1)

array([[ 1.,  1.,  1.],
       [ 5., -5.,  0.]])

Let's write a function called switch_rows which takes 3 input parameters <b><i>A,i</i></b>  and <b><i>j</i></b> and returns the matrix that results from switching rows <b><i>i</i></b> and <b><i>j</i></b> in the matrix <b><i>A</i></b>.

In [41]:
def switch_rows(A,i,j):
    "Switch rows i and j in matrix A."
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = 0
    E[j,j] = 0
    E[i,j] = 1
    E[j,i] = 1
    return E @ A

In [42]:
A = np.array([[1,1,1],[1,-1,0]])
print(A)

[[ 1  1  1]
 [ 1 -1  0]]


In [43]:
switch_rows(A,0,1)

array([[ 1., -1.,  0.],
       [ 1.,  1.,  1.]])

# Examples

<h2>Find the Inverse</h2>

<img src="linearmath8.png">

In [45]:
M = np.array([[5,4,2],[-1,2,1],[1,1,1]])
print(M)

[[ 5  4  2]
 [-1  2  1]
 [ 1  1  1]]


In [46]:
A = np.hstack([M,np.eye(3)])
print(A)

[[ 5.  4.  2.  1.  0.  0.]
 [-1.  2.  1.  0.  1.  0.]
 [ 1.  1.  1.  0.  0.  1.]]


In [47]:
A1 = switch_rows(A,0,2)
print(A1)

[[ 1.  1.  1.  0.  0.  1.]
 [-1.  2.  1.  0.  1.  0.]
 [ 5.  4.  2.  1.  0.  0.]]


In [48]:
A2 = add_row(A1,1,1,0)
print(A2)

[[1. 1. 1. 0. 0. 1.]
 [0. 3. 2. 0. 1. 1.]
 [5. 4. 2. 1. 0. 0.]]


In [49]:
A3 = add_row(A2,-5,2,0)
print(A3)

[[ 1.  1.  1.  0.  0.  1.]
 [ 0.  3.  2.  0.  1.  1.]
 [ 0. -1. -3.  1.  0. -5.]]


In [50]:
A4 = switch_rows(A3,1,2)
print(A4)

[[ 1.  1.  1.  0.  0.  1.]
 [ 0. -1. -3.  1.  0. -5.]
 [ 0.  3.  2.  0.  1.  1.]]


In [51]:
A5 = scale_row(A4,-1,1)
print(A5)

[[ 1.  1.  1.  0.  0.  1.]
 [ 0.  1.  3. -1.  0.  5.]
 [ 0.  3.  2.  0.  1.  1.]]


In [52]:
A6 = add_row(A5,-3,2,1)
print(A6)

[[  1.   1.   1.   0.   0.   1.]
 [  0.   1.   3.  -1.   0.   5.]
 [  0.   0.  -7.   3.   1. -14.]]


In [53]:
A7 = scale_row(A6,-1/7,2)
print(A7)

[[ 1.          1.          1.          0.          0.          1.        ]
 [ 0.          1.          3.         -1.          0.          5.        ]
 [ 0.          0.          1.         -0.42857143 -0.14285714  2.        ]]


In [54]:
A8 = add_row(A7,-3,1,2)
print(A8)

[[ 1.          1.          1.          0.          0.          1.        ]
 [ 0.          1.          0.          0.28571429  0.42857143 -1.        ]
 [ 0.          0.          1.         -0.42857143 -0.14285714  2.        ]]


In [55]:
A9 = add_row(A8,-1,0,2)
print(A9)

[[ 1.          1.          0.          0.42857143  0.14285714 -1.        ]
 [ 0.          1.          0.          0.28571429  0.42857143 -1.        ]
 [ 0.          0.          1.         -0.42857143 -0.14285714  2.        ]]


In [56]:
A10 = add_row(A9,-1,0,1)
print(A10)

[[ 1.          0.          0.          0.14285714 -0.28571429  0.        ]
 [ 0.          1.          0.          0.28571429  0.42857143 -1.        ]
 [ 0.          0.          1.         -0.42857143 -0.14285714  2.        ]]


Let's verify that we found the inverse <b><i>M<sup>-1</sup></i></b> correctly:

In [57]:
Minv = A10[:,3:]
print(Minv)

[[ 0.14285714 -0.28571429  0.        ]
 [ 0.28571429  0.42857143 -1.        ]
 [-0.42857143 -0.14285714  2.        ]]


In [58]:
result = Minv @ M
print(result)

[[ 1.00000000e+00  4.44089210e-16  2.22044605e-16]
 [-6.66133815e-16  1.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


Success! We can see the result more clearly if we round to 15 decimal places:

In [59]:
np.round(result,15)

array([[ 1.e+00,  0.e+00,  0.e+00],
       [-1.e-15,  1.e+00, -0.e+00],
       [ 0.e+00,  0.e+00,  1.e+00]])

<h3>Solve a System</h3>
Let's use our functions to perform Gaussian elimination and solve a linear system of equations <b>Ax = b</b>.

In [60]:
A = np.array([[6,15,1],[8,7,12],[2,7,8]])
print(A)

[[ 6 15  1]
 [ 8  7 12]
 [ 2  7  8]]


In [61]:
b = np.array([[2],[14],[10]])
print(b)

[[ 2]
 [14]
 [10]]


Form the augemented matrix <b><i>M</i></b>:

In [62]:
M = np.hstack([A,b])
print(M)

[[ 6 15  1  2]
 [ 8  7 12 14]
 [ 2  7  8 10]]


Perform row operations:

In [63]:
M1 = scale_row(M,1/6,0)
print(M1)

[[ 1.          2.5         0.16666667  0.33333333]
 [ 8.          7.         12.         14.        ]
 [ 2.          7.          8.         10.        ]]


In [64]:
M2 = add_row(M1,-8,1,0)
print(M2)

[[  1.           2.5          0.16666667   0.33333333]
 [  0.         -13.          10.66666667  11.33333333]
 [  2.           7.           8.          10.        ]]


In [65]:
M3 = add_row(M2,-2,2,0)
print(M3)

[[  1.           2.5          0.16666667   0.33333333]
 [  0.         -13.          10.66666667  11.33333333]
 [  0.           2.           7.66666667   9.33333333]]


In [66]:
M4 = scale_row(M3,-1/13,1)
print(M4)

[[ 1.          2.5         0.16666667  0.33333333]
 [ 0.          1.         -0.82051282 -0.87179487]
 [ 0.          2.          7.66666667  9.33333333]]


In [67]:
M5 = add_row(M4,-2,2,1)
print(M5)

[[ 1.          2.5         0.16666667  0.33333333]
 [ 0.          1.         -0.82051282 -0.87179487]
 [ 0.          0.          9.30769231 11.07692308]]


In [68]:
M6 = scale_row(M5,1/M5[2,2],2)
print(M6)

[[ 1.          2.5         0.16666667  0.33333333]
 [ 0.          1.         -0.82051282 -0.87179487]
 [ 0.          0.          1.          1.19008264]]


In [69]:
M7 = add_row(M6,-M6[1,2],1,2)
print(M7)

[[1.         2.5        0.16666667 0.33333333]
 [0.         1.         0.         0.1046832 ]
 [0.         0.         1.         1.19008264]]


In [70]:
M8 = add_row(M7,-M7[0,2],0,2)
print(M8)

[[1.         2.5        0.         0.13498623]
 [0.         1.         0.         0.1046832 ]
 [0.         0.         1.         1.19008264]]


In [71]:
M9 = add_row(M8,-M8[0,1],0,1)
print(M9)

[[ 1.          0.          0.         -0.12672176]
 [ 0.          1.          0.          0.1046832 ]
 [ 0.          0.          1.          1.19008264]]


Success! The solution of <b>Ax = b</b> is

In [72]:
x = M9[:,3].reshape(3,1)
print(x)

[[-0.12672176]
 [ 0.1046832 ]
 [ 1.19008264]]


Or, we can do it the easy way...

In [73]:
x = la.solve(A,b)
print(x)

[[-0.12672176]
 [ 0.1046832 ]
 [ 1.19008264]]


<h3>scipy.linalg.solve</h3>
We are mostly interested in linear systems <b>Ax = b</b>  where there is a unique solution <b>x</b>. This is the case when <b>A</b> is a square matrix (m = n) and <b>det(A) != 0</b> . To solve such a system, we can use the function <b>scipy.linalg.solve<b>.

    The function returns a solution of the system of equations <b>Ax = b</b>. For example:

In [74]:
A = np.array([[1,1],[1,-1]])
print(A)

[[ 1  1]
 [ 1 -1]]


In [75]:
b1 = np.array([2,0])
print(b1)

[2 0]


And solve:

In [76]:
x1 = la.solve(A,b1)
print(x1)

[1. 1.]


Note that the output <b>x</b> is returned as a 1D NumPy array when the vector <b>b</b> (the right hand side) is entered as a 1D NumPy array. If we input <b>b</b> as a 2D NumPy array, then the output is a 2D NumPy array. For example:

In [77]:
A = np.array([[1,1],[1,-1]])
b2 = np.array([2,0]).reshape(2,1)
x2 = la.solve(A,b2)
print(x2)

[[1.]
 [1.]]


Finally, if the right hand side <b>b</b> is a matrix, then the output is a matrix of the same size. It is the solution of <b>Ax = b</b> when <b>b</b> is a matrix. For example:

In [78]:
A = np.array([[1,1],[1,-1]])
b3 = np.array([[2,2],[0,1]])
x3 = la.solve(A,b3)
print(x3)

[[1.  1.5]
 [1.  0.5]]


<img src="linearmath9.png">

In [80]:
A = np.array([[2,1],[1,1]])
print(A)

[[2 1]
 [1 1]]


And the vector b:

In [81]:
b = np.array([1,-1]).reshape(2,1)
print(b)

[[ 1]
 [-1]]


And solve:

In [83]:
x = la.solve(A,b)
print(x)

[[ 2.]
 [-3.]]


We can verify the solution by computing the inverse of A:

In [84]:
Ainv = la.inv(A)
print(Ainv)

[[ 1. -1.]
 [-1.  2.]]


And multiply <b>A<sup>-1</sup>b</b> to solve for x:

In [85]:
x = Ainv @ b
print(x)

[[ 2.]
 [-3.]]


We get the same result. Success!

<h3>Inverse or Solve</h3>
It's a bad idea to use the inverse <b>A<sup>-1</sup></b> to solve <b>Ax = b</b> if <b>A</b> is large. It's too computationally expensive. Let's create a large random matrix <b>A</b> and vector <b>b</b> and compute the solution <b>x</b> in 2 ways:

In [86]:
N = 1000
A = np.random.rand(N,N)
b = np.random.rand(N,1)

Check the first entries A:

In [87]:
A[:3,:3]

array([[0.92891026, 0.10749158, 0.18345294],
       [0.32793688, 0.02207131, 0.4253631 ],
       [0.56208307, 0.29542629, 0.25138688]])

And for b:

In [88]:
b[:4,:]

array([[0.3172392 ],
       [0.84883666],
       [0.70673025],
       [0.70510265]])

Now we compare the speed of <b>scipy.linalg.solve</b> with <b>scipy.linalg.inv</b>:

In [89]:
%%timeit
x = la.solve(A,b)

22.3 ms ± 1.24 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [90]:
%%timeit
x = la.inv(A) @ b

31.4 ms ± 1.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Solving with scipy.linalg.solve is about twice as fast!

