# Linear Algebra with SciPy

The main Python package for linear algebra is the SciPy subpackage <b>scipy.linalg</b> which builds on NumPy. Let's import both packages:

In [1]:
import numpy as np
import scipy.linalg as la

<h3>NumPy Arrays</h3>
Let's begin with a quick review of NumPy arrays. We can think of a 1D NumPy array as a list of numbers. We can think of a 2D NumPy array as a matrix. And we can think of a 3D array as a cube of numbers. When we select a row or column from a 2D NumPy array, the result is a 1D NumPy array (called a slice). This is different from MATLAB where when you select a column from a matrix it's returned as a column vector which is a 2D MATLAB matrix.

It can get a bit confusing and so we need to keep track of the shape, size and dimension of our NumPy arrays.

<h3>Array Attributes</h3>
Create a 1D (one-dimensional) NumPy array and verify its dimensions, shape and size.

In [2]:
a = np.array([1,3,-2,1])
print(a)

[ 1  3 -2  1]


Verify the number of dimensions:

In [3]:
a.ndim

1

Verify the shape of the array:

In [4]:
a.shape

(4,)

The shape of an array is returned as a Python tuple. The output in the cell above is a tuple of length 1. And we verify the size of the array (ie. the total number of entries in the array):

In [5]:
a.size

4

Create a 2D (two-dimensional) NumPy array (ie. matrix):

In [6]:
M = np.array([[1,2],[3,7],[-1,5]])
print(M)

[[ 1  2]
 [ 3  7]
 [-1  5]]


Verify the number of dimensions:

In [7]:
M.ndim

2

Verify the shape of the array:

In [9]:
M.shape

(3, 2)

Finally, verify the total number of entries in the array:

In [11]:
M.size

6

Select a row or column from a 2D NumPy array and we get a 1D array:

In [12]:
col = M[:,1] 
print(col)

[2 7 5]


Verify the number of dimensions of the slice:

In [13]:
col.ndim

1

Verify the shape and size of the slice:

In [15]:
col.shape

(3,)

In [16]:
col.size

3

When we select a row of column from a 2D NumPy array, the result is a 1D NumPy array. However, we may want to select a column as a 2D column vector. This requires us to use the reshape method.

For example, create a 2D column vector from the 1D slice selected from the matrix M above:

In [17]:
print(col)

[2 7 5]


In [18]:
column = np.array([2,7,5]).reshape(3,1)
print(column)

[[2]
 [7]
 [5]]


Verify the dimensions, shape and size of the array:

In [19]:
print('Dimensions:', column.ndim)
print('Shape:', column.shape)
print('Size:', column.size)

Dimensions: 2
Shape: (3, 1)
Size: 3


The variables col and column are different types of objects even though they have the "same" data

In [20]:
print(col)

[2 7 5]


In [21]:
print('Dimensions:',col.ndim)
print('Shape:',col.shape)
print('Size:',col.size)

Dimensions: 1
Shape: (3,)
Size: 3


<h3>Matrix Operations and Functions</h3>
<h2>Arithmetic Operations</h2>
Recall that arithmetic array operations +, -, /, * and ** are performed elementwise on NumPy arrays. Let's create a NumPy array and do some computations:

In [22]:
M = np.array([[3,4],[-1,5]])
print(M)

[[ 3  4]
 [-1  5]]


In [23]:
M * M

array([[ 9, 16],
       [ 1, 25]])

<h3>Matrix Multiplication</h3>
We use the @ operator to do matrix multiplication with NumPy arrays:

In [24]:
M @ M

array([[ 5, 32],
       [-8, 21]])

<img src="linearmath1.png"/>

In [25]:
A = np.array([[1,3],[-1,7]])
print(A)

[[ 1  3]
 [-1  7]]


In [26]:
B = np.array([[5,2],[1,2]])
print(B)

[[5 2]
 [1 2]]


In [27]:
I = np.eye(2)
print(I)

[[1. 0.]
 [0. 1.]]


In [28]:
2*I + 3*A - A@B

array([[-3.,  1.],
       [-5., 11.]])

<h3>Matrix Powers</h3>
There's no symbol for matrix powers and so we must import the function matrix_power from the subpackage numpy.linalg.

In [29]:
from numpy.linalg import matrix_power as mpow

In [30]:
M = np.array([[3,4],[-1,5]])
print(M)

[[ 3  4]
 [-1  5]]


In [31]:
mpow(M,2)

array([[ 5, 32],
       [-8, 21]])

In [32]:
mpow(M,5)

array([[-1525,  3236],
       [ -809,    93]])

Compare with the matrix multiplcation operator:

In [33]:
M @ M @ M @ M @ M

array([[-1525,  3236],
       [ -809,    93]])

In [34]:
mpow(M,3)

array([[-17, 180],
       [-45,  73]])

In [35]:
M @ M @ M

array([[-17, 180],
       [-45,  73]])

<h3>Tranpose</h3>
We can take the transpose with <b>.T</b> attribute:

In [36]:
print(M)

[[ 3  4]
 [-1  5]]


In [37]:
print(M.T)

[[ 3 -1]
 [ 4  5]]


Notice that <b>M M<sup>T</sup></b>  is a symmetric matrix:

In [38]:
M @ M.T

array([[25, 17],
       [17, 26]])

<h3>Inverse</h3>
We can find the inverse using the function <b>scipy.linalg.inv<b>:

In [39]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [40]:
la.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

<h3>Trace</h3>
We can find the trace of a matrix using the function <b>numpy.trace</b>:

In [42]:
np.trace(A)

5

<h3>Norm</h3>
Under construction

<h3>Determinant</h3>
We find the determinant using the function scipy.linalg.det:

In [43]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [44]:
la.det(A)

-2.0

<h3>Dot Product</h3>
Under construction

<img src="linearmath2.png">

In [46]:
print(A)

[[1 2]
 [3 4]]


In [47]:
trace_A = np.trace(A)
det_A = la.det(A)
I = np.eye(2)
A @ A - trace_A * A + det_A * I

array([[0., 0.],
       [0., 0.]])

Let's do this again for some random matrices:

In [48]:
N = np.random.randint(0,10,[2,2])
print(N)

[[0 7]
 [5 4]]


In [49]:
trace_N = np.trace(N)
det_N = la.det(N)
I = np.eye(2)
N @ N - trace_N * N + det_N * I

array([[0., 0.],
       [0., 0.]])

<img src="linearmath3.png">

In [51]:
def proj(v,w):
    '''Project vector v onto w.'''
    v = np.array(v)
    w = np.array(w)
    return np.sum(v * w)/np.sum(w * w) * w   # or (v @ w)/(w @ w) * w


In [52]:
proj([1,2,3],[1,1,1])

array([2., 2., 2.])